* CSCI 13500 - Daedalus

| Meets        | Monday Thursday 10:00 - 10:50 |
| Room         | Hunter North  C107 |
| Instructor   | Mike Zamansky                                                              |
| Email        | mz631@hunter.cuny.edu                                                      |
| Office       | 1001K Hunter North                                                         |
| Office Hours | By appointment                                                             |


* Main Syllabus Link

- [[https://maryash.github.io/135/index.html][Main 135 page]]


* Getting help

Use Zulip for help. These streams in particular:

- #135 this goes to everyone in our section
- #2022 goes to all members of the current first year Daedalus cohort
- #general the Daedalus members

There are also tutoring sessions listed on
the main 135 lecture page (see above).

* Class policies and grading

** Grading

- Labs will be graded on a 0 - 10 scale.
- Unless otherwise noted labs will be released Mondays after class and
  will be due Friday of the same week at 8:00am.
- Lab specifications are different for our recitation than for the
  other recitations. Specifics will be written in the lab
  assignments. 
- Most labs will be completed outside of class time as homework
  assignments however some will take place during or will replace some
  synchronous class time.
- Our section will include additional labs and some of the labs will
  include additional material. 
- Assuming all labs are assigned and completed, the lowest grade will
  not be included in calculating the lab average.
- If a lab cannot be completed on time, you are expected to discuss
  this with the instructor prior to the due date/time. Under some
  circumstances the instructor might accept work submitted or updated
  after the due date/time. Otherwise, late labs will not be accepted
- Labs will be compiled, run, and tested under Linux. It is the students 
  responsiblity to ensure that their labs work on this platform.
- Labs will not be regraded.

** Differences from the non Daedalus sections 

- We will *not* be using Gradescope for our labs. That said, you are
  expected to use *Gradescope* and follow all requirements for the
  main lecture. So, while you will use GitHub for our labs, you will
  submit projects, take tests, complete homework assignments and
  problem sets following the main 135 instructors directions.


** Cameras during synchronous classes 

Students are asked to have their cameras on during synchronous classes
as this makes the class feel more like a community. If a student does
not wish or is unable to comply with this request they must disucss
this with the instructor the instructor 

* Lab instructions 

This recitation *will not* be using Gradescope for our labs. Instead,
we are using GitHub Classroom. An email will be posted on Zulip with a
link when each lab is released. 

Students should:

1. Accept the assignment
2. Clone the repo to their local machine.
3. Complete the lab as instructed

Labs will be graded on the instructors Linux computer so you should be
sure that your solutions will compile and run as instructed on that
platform. Also, only include source files and other files explicitly
asked for in your repository. Do not add executable files (a.out, for
instance) or object (.o) files to the repository.

*Due Dates:* Unless otherwise noted, labs will be released on Mondays
 after class and will be due the Friday morning of that week at
 8:00am.

* Emacs links
- [[https://www.masteringemacs.org/reading-guide][Mastering Emacs reading guide]]
- [[http://sachachua.com/blog/2013/05/how-to-learn-emacs-a-hand-drawn-one-pager-for-beginners/][How to learn Emacs]]
- [[http://cestlaz.github.io/stories/emacs][Using Emacs video series]]

* Resources
** C++
- John Sterlings C++ Class Notes: http://cis.poly.edu/jsterling/cs2124/

** Unix Command Line / Shell
1) [[https://hellowebbooks.com/learn-command-line/][Learn the Command Line]] - Mac version
2) [[https://www.codecademy.com/learn/learn-the-command-line][Learn the Command Line]]
3) [[http://linuxcommand.org/]]
4) https://hellowebbooks.com/learn-command-line/
