# This is a Makefile 

tree:	find_plot dig_a_hole
	@echo "Planting the tree"
main: main.cpp
	g++ -o main main.cpp

help:
	@echo "This is some help info"
	@echo "we can have multiple lines as actions"


find_plot:
	@echo "I found a place for the tree"

dig_a_hole: find_a_shovel
	@echo "digging a hole"

find_a_shovel:
	@echo "found a shovel"
